version: "2"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
